create table offers(
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description varchar(500),
    city varchar(15),
    minimumWage int,
    status varchar(10),
    refCustomer int  NOT NULL,
    startDay DATE,
    activity varchar(50),
    FOREIGN KEY(refCustomer) REFERENCES CUSTOMER(ID)
);